enum HeroTags {
  PAGE_TITLE,
  PAGE_INFO_ICON,
  PAGE_INFO_TEXT,
  PAGE_INFO_CARD,
  PAGE_FILTER_OPTIONS,
  DRAWER_ACTIVE_INDICATOR,
  PROJECT_TITLE,
  NO_DATA_IMAGE,
  NO_DATA_TEXT,
  ACCOUNT_BUTTON,
}
