name: messdienerplan_webinterface
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.7.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  json_serializable: ^4.1.3
  kiwi: ^3.0.0
  logger: ^1.0.0
  meta: ^1.3.0
  provider: ^5.0.0
  retrofit: ^2.0.0
  shared_preferences: ^2.0.6
  vrouter: ^1.1.4+3

dev_dependencies:
  build_runner: ^2.0.5
  lint: ^1.5.3
  retrofit_generator: ^2.0.0+3

flutter:
  uses-material-design: true