# This is a basic workflow to help you get started with Actions

name: Flutter CD
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  flutter-build:
    name: Flutter Projekt bauen
    runs-on: ubuntu-latest
    steps:
      - 
        name: Repository checkouten
        uses: actions/checkout@v2
      - 
        name: Flutter im Beta Channel installieren
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - 
        name: Projekt für Web bauen (html renderer)
        run: flutter build web --web-renderer html
      - 
        name: Build Artefakte hochladen
        uses: actions/upload-artifact@master
        with:
          name: flutter artifacts
          path: build/web/
        
  build-and-push:
    name: Docker Container bauen und hochladen
    runs-on: ubuntu-latest
    needs: [flutter-build]
    steps:
      - 
        name: Repository checkouten
        uses: actions/checkout@v2
      -
        name: Vorbereiten
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/hauketoenjes/messdienerplan_webinterface
          VERSION=noop
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=latest
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - 
        name: Flutter Artefakte vom Build herunterladen
        uses: actions/download-artifact@master
        with:
          name: flutter artifacts
          path: build/web
       
      - 
        name: BuildX installieren
        uses: docker/setup-buildx-action@v1
      -
        name: In ghcr.io einloggen
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PUSH }}
      -
         name: Docker Container bauen und hochladen
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./Dockerfile
           push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.prep.outputs.tags }} 
